### ISSUE TITLE
Generate hyperlink for sub-menu parent folder

### ISSUE THREAD

**Issue by that-joao** [PaulieScanlon/gatsby-mdx-routes#5]
This issue is a follow up to the question on [this tweet](https://twitter.com/unispheredesign/status/1221880961341829120).

Adding an `index.mdx` file inside a sub-menu folder should make that folder an hyperlink.

Take the following folder and file structure:

```
|-- src
    |-- pages
        |-- other-pages
           |-- some-other-page.mdx
        |-- yet-another-pages
           |-- index.mdx
           |-- yet-another-page.mdx
        |-- about.mdx
        |-- contact.mdx
        |-- index.mdx
```

The following menu should be rendered:

```
other pages (no link)
    some other page (link to: /other-pages/some-other-page)
yet another pages (link to: /yet-another-pages)
    yet another page (link to: /yet-another-pages/yet-another-page)
about (link to: /about)
contact (link to: /contact)
home (link to: /home)
```

Take special not to the 3rd line in the above code.

**Comment by that-joao** [comment]
Another way of achieving this is like the following file/folder structure:

```
|-- src
    |-- pages
        |-- other-pages.mdx
        |-- other-pages
           |-- some-other-page.mdx
```

which should generate the following menu:

```
other pages (link to: /other-pages)
    some other page (link to: /other-pages/some-other-page)
```

Actually like this approach better to be honest.

Let me know what you think.

**Comment by PaulieScanlon** [comment]
Hey @unisphere thanks for raising the issue. 

I think the problem here is, originally i had intended this plugin to mirror the directory structure of your project. 

In your example above `yet-another-page` would actually be a folder. 

I think at the moment it would be too complicated to attempt to determine what is a folder and what is a file without using something much more complicated than `slug ? true : false`.

I guess the other thing is because the menus array is created recursively it does the same for everything on every loop and to ask it to break the recursive loop based on a condition would require either an additional frontmatter field or some other method of telling it what the special cases are. 

In either scenario it makes the code more complicated and potentially makes it harder to use the plugin.

I appreciate your time for raising the issue but i've given it some thought and for now i'm going to mark is as #wontfix

**Comment by that-joao** [comment]
Hey @PaulieScanlon , no problem, I understand the constraints. Determining what a folder is would absolutely need more metadata which makes things more confusing indeed.

Cheers!
